name: Build and deploy Python app to Azure Web App - videoapp

# ─── MUST add at the root so every job gets OIDC ───────────────────────────────
permissions:
  id-token: write   # <— allows GitHub to mint an OIDC token
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Dump OIDC info (debug)
        shell: bash
        run: |
          echo "OIDC URL:  $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "OIDC TOKEN (truncated): ${ACTIONS_ID_TOKEN_REQUEST_TOKEN:0:20}..."
          # try fetching the actual JWT
          curl -s \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL" \
            || echo "❌ failed to get ID token"

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          audience: api://AzureADTokenExchange

      - name: Verify Az CLI context
        run: |
          az account show

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'videoapp'
          slot-name: 'Production'
