name: Build and deploy Python app to Azure Web App - videoapp

# ─── MUST be at the very top ────────────────────────────────────────────────
permissions:
  id-token: write    # allows OIDC tokens
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and activate venv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Debug OIDC token issuance
        shell: bash
        run: |
          echo "== ACTIONS_ID_TOKEN_REQUEST_URL =="
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "== ACTIONS_ID_TOKEN_REQUEST_TOKEN (first 100 chars) =="
          echo "${ACTIONS_ID_TOKEN_REQUEST_TOKEN:0:100}..."
          # fail early if no token
          test -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" || (echo "✖️ No ID token!" && exit 1)

      - name: Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          audience: api://AzureADTokenExchange

      - name: Verify Azure login
        run: az account show

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'videoapp'
          slot-name: 'Production'
