name: Build and deploy Python app to Azure Web App - videoapp

# ─── Root-level permissions ENABLE OIDC issuance ──────────────────────────────
permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: actions/setup-python@v5
        name: Set up Python
        with:
          python-version: '3.11'

      - name: Create and activate venv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        name: Download artifact
        with:
          name: python-app

      - name: Debug OIDC token issuance
        shell: bash
        run: |
          echo "=== REQUEST URL ==="
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "=== TOKEN (first 200 chars) ==="
          echo "${ACTIONS_ID_TOKEN_REQUEST_TOKEN:0:200}"
          # fail if empty
          test -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" || (echo "✖️ No ID token!" && exit 1)

      - name: Login to Azure via OIDC (explicit)
        uses: azure/login@v1.4.3
        with:
          auth-type: oidc
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          audience: api://AzureADTokenExchange

      - name: Verify Azure login
        run: az account show

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'videoapp'
          slot-name: 'Production'
